platform :ios, '7.0'
workspace 'Gusty'
xcodeproj 'Gusty/Gusty.xcodeproj'
pod 'DTFoundation'
pod 'Google-AdMob-Ads-SDK'
pod 'FlurrySDK'
pod 'MTStatusBarOverlay'
pod 'OCHamcrest'
pod 'OCMock'
pod 'ODRefreshControl'
pod 'MWFeedParser'
