platform :ios, '7.0'
workspace 'GustyLib'
xcodeproj 'GustyLib/GustyLib.xcodeproj'
link_with 'GustyLibTests'

pod 'DTFoundation'
pod 'Google-AdMob-Ads-SDK'
pod 'FlurrySDK'
pod 'MTStatusBarOverlay'
pod 'OCHamcrest'
pod 'OCMock'
pod 'ODRefreshControl'
pod 'MWFeedParser'
