platform :ios, '7.0'
workspace 'GustyLib'
xcodeproj 'GustyLib/GustyLib.xcodeproj'
link_with 'GustyLibTests'

pod 'DTFoundation'
pod 'Google-AdMob-Ads-SDK'
pod 'FlurrySDK'
pod 'MTStatusBarOverlay'
pod 'OCHamcrest'
pod 'OCMock'
pod 'ODRefreshControl'
pod 'MWFeedParser'

pod 'IFATestingSupport', :git => 'https://bitbucket.org/marcelo_schroeder/ifatestingsupport.git', :tag => '0.1.1'
# pod 'IFATestingSupport', :path => '/Users/mschroeder/myfiles/projects/Xcode5/IFATestingSupport/IFATestingSupport_development'
