//
//  IFAConstants.h
//  Gusty
//
//  Created by Marcelo Schroeder on 24/06/10.
//  Copyright 2010 InfoAccent Pty Limited. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

static CGFloat const IA_TABLE_VIEW_EDITING_CELL_X_OFFSET = 32;
static CGFloat const IA_TABLE_SECTION_HEADER_DEFAULT_HEIGHT = 22;
static CGFloat const IA_FORM_SECTION_HEADER_DEFAULT_HEIGHT = 39;
static CGFloat const IA_MINIMUM_TAP_AREA_DIMENSION = 44;
static CGFloat const IA_TABLE_VIEW_CELL_SEPARATOR_DEFAULT_INSET_LEFT = 15;
static NSTimeInterval const IA_UI_ANIMATION_DURATION = 0.3;

@interface IFAConstants : NSObject {

}

extern NSString* const IA_BUTTON_LABEL_SAVE;
extern NSString* const IA_BUTTON_LABEL_CANCEL;

extern NSString* const IA_ERROR_DOMAIN_COMMON;

extern NSString* const IA_CACHE_KEY_ENTITY_CONFIG_DICTIONARY;
extern NSString* const IA_CACHE_KEY_MENU_VIEW_CONTROLLERS_DICTIONARY;

// Notifications
extern NSString* const IA_NOTIFICATION_PERSISTENT_ENTITY_CHANGE;
extern NSString* const IA_NOTIFICATION_CONTEXT_SWITCH_REQUEST;
extern NSString* const IA_NOTIFICATION_CONTEXT_SWITCH_REQUEST_GRANTED;
extern NSString* const IA_NOTIFICATION_CONTEXT_SWITCH_REQUEST_DENIED;
extern NSString* const IA_NOTIFICATION_NAVIGATION_EVENT;
extern NSString* const IA_NOTIFICATION_MENU_BAR_BUTTON_ITEM_INVALIDATED;
extern NSString* const IA_NOTIFICATION_LOCATION_AUTHORIZATION_STATUS_CHANGE;
extern NSString* const IA_NOTIFICATION_ADS_SUSPEND_REQUEST;
extern NSString* const IA_NOTIFICATION_ADS_RESUME_REQUEST;

// Dictionary Keys
extern NSString* const IA_KEY_INSERTED_OBJECTS;
extern NSString* const IA_KEY_UPDATED_OBJECTS;
extern NSString* const IA_KEY_DELETED_OBJECTS;
extern NSString* const IA_KEY_UPDATED_PROPERTIES;
extern NSString* const IA_KEY_ORIGINAL_PROPERTIES;
extern NSString* const IA_KEY_THREAD_SAFE_CALENDAR;
extern NSString* const IA_KEY_SERIAL_QUEUE_MANAGED_OBJECT_CONTEXT;

// Entity Config
extern NSString* const IA_ENTITY_CONFIG_FORM_NAME_DEFAULT;
extern NSString* const IA_ENTITY_CONFIG_FORM_NAME_CREATION_SHORTCUT;

// Info Plist
extern NSString* const IA_INFOPLIST_PREFERENCES_CLASS_NAME;

/* enums */

enum {

    IA_ERROR_PERSISTENCE_VALIDATION		= 1000,
    IA_ERROR_PERSISTENCE_DUPLICATE_KEY  = 1010,

    IA_UIVIEW_TAG_ACTION_SHEET_CANCEL   = 2000,
    IA_UIVIEW_TAG_ACTION_SHEET_DELETE	= 2010,
    IA_UIVIEW_TAG_HELP_BACKGROUND       = 2020,
    IA_UIVIEW_TAG_HELP_FOREGROUND       = 2030,
    IA_UIVIEW_TAG_HELP_POP_TIP          = 2040,
    IA_UIVIEW_TAG_HELP_BUTTON           = 2050,
    
    IA_UIBAR_ITEM_TAG_HELP_BUTTON               = 2500,
    IA_UIBAR_ITEM_TAG_EDIT_BUTTON               = 2510,
    IA_UIBAR_ITEM_TAG_BACK_BUTTON               = 2520, // custom back button
    IA_UIBAR_ITEM_TAG_LEFT_SLIDING_PANE_BUTTON  = 2530, // split view controller master on iPad, left under view on iPhone
    IA_UIBAR_ITEM_TAG_FIXED_SPACE_BUTTON        = 2540, // bar button item spacing automation

	IA_UIBAR_BUTTON_ITEM_ADD			= 3000,
	IA_UIBAR_BUTTON_ITEM_DELETE			= 3010,
	IA_UIBAR_BUTTON_ITEM_SELECT_NONE	= 3020,
	IA_UIBAR_BUTTON_ITEM_CANCEL			= 3030,
	IA_UIBAR_BUTTON_ITEM_FLEXIBLE_SPACE = 3040,
	IA_UIBAR_BUTTON_ITEM_DONE			= 3050,
	IA_UIBAR_BUTTON_PREVIOUS_PAGE		= 3080,
	IA_UIBAR_BUTTON_NEXT_PAGE           = 3090,
	IA_UIBAR_BUTTON_ITEM_SELECT_NOW		= 3120,
	IA_UIBAR_BUTTON_ITEM_FIXED_SPACE	= 3170,
	IA_UIBAR_BUTTON_ITEM_SELECT_ALL		= 3180,
	IA_UIBAR_BUTTON_ITEM_ACTION         = 3210,
	IA_UIBAR_BUTTON_ITEM_SELECT_TODAY	= 3220,
	IA_UIBAR_BUTTON_ITEM_REFRESH        = 3230,
	IA_UIBAR_BUTTON_ITEM_DISMISS        = 3240,
	IA_UIBAR_BUTTON_ITEM_BACK           = 3250,
	
};

/* typedefs */

typedef enum {

	IA_DURATION_FORMAT_DECIMAL_HOURS,
	IA_DURATION_FORMAT_HOURS_MINUTES,
	IA_DURATION_FORMAT_HOURS_MINUTES_SECONDS,
	IA_DURATION_FORMAT_FULL,
	IA_DURATION_FORMAT_HOURS_MINUTES_LONG,
	IA_DURATION_FORMAT_HOURS_MINUTES_SECONDS_LONG,
	IA_DURATION_FORMAT_FULL_LONG,

} IADurationFormat;

typedef enum {
	
	IA_EDITOR_TYPE_TEXT,
	IA_EDITOR_TYPE_DATE_PICKER,
	IA_EDITOR_TYPE_SELECTION_LIST,
	IA_EDITOR_TYPE_FORM,
	IA_EDITOR_TYPE_SEGMENTED,
	IA_EDITOR_TYPE_PICKER,
	IA_EDITOR_TYPE_SWITCH,
	IA_EDITOR_TYPE_NUMBER,
    IA_EDITOR_TYPE_TIME_INTERVAL,
    IA_EDITOR_TYPE_FULL_DATE_AND_TIME,
    IA_EDITOR_TYPE_NOT_APPLICABLE,

} IAEditorType;

typedef enum {
    
    IA_DATA_TYPE_TIME_INTERVAL,
    
} IADataType;

typedef enum {
    IA_UISCROLL_PAGE_LEFT_FAR,
    IA_UISCROLL_PAGE_LEFT_NEAR,
    IA_UISCROLL_PAGE_CENTRE,
    IA_UISCROLL_PAGE_RIGHT_NEAR,
    IA_UISCROLL_PAGE_RIGHT_FAR,
    IA_UISCROLL_PAGE_INIT,
} IAUIScrollPage;

typedef enum IAUITableSectionHeaderType : NSUInteger {
    IA_UITABLE_SECTION_HEADER_TYPE_LIST,
    IA_UITABLE_SECTION_HEADER_TYPE_FORM,
} IAUITableSectionHeaderType;

@end
